# Exported from Render on 2025-03-25T19:38:35Z
services:
- type: web
  name: backend-restaurantes
  runtime: node
  repo: https://github.com/Luisferrer02/backend-restaurantes
  plan: free
  envVars:
  - key: GOOGLE_PLACES_API_KEY
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: MONGO_URI
    sync: false
  region: frankfurt
  buildCommand: npm install
  startCommand: node server.js
version: "1"
